default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: persan_development
test:
  <<: *default
  database: persan_test

production:
  <<: *default
  database: persan_production

